import { NextFont } from 'next/dist/compiled/@next/font';

export const set_all_fonts = (baseFont: NextFont, theme: any) => {
  return {
    typography: {
      fontFamily: baseFont.style.fontFamily,

      h1: {
        fontFamily: baseFont.style.fontFamily,
        fontWeight: theme?.typography?.h1?.fontWeight,
        lineHeight: theme?.typography?.h1?.lineHeight,
        fontSize: theme?.typography?.h1?.fontSize,
        letterSpacing: theme?.typography?.h1?.letterSpacing,
        paragraphSpacing: theme?.typography?.h1?.paragraphSpacing,
        paragraphIndent: theme?.typography?.h1?.paragraphIndent,
        textCase: theme?.typography?.h1?.textCase,
        textDecoration: theme?.typography?.h1?.textDecoration,
      },
      h2: {
        fontFamily: baseFont.style.fontFamily,
        fontWeight: theme?.typography?.h2?.fontWeight,
        lineHeight: theme?.typography?.h2?.lineHeight,
        fontSize: theme?.typography?.h2?.fontSize,
        letterSpacing: theme?.typography?.h2?.letterSpacing,
        paragraphSpacing: theme?.typography?.h2?.paragraphSpacing,
        paragraphIndent: theme?.typography?.h2?.paragraphIndent,
        textCase: theme?.typography?.h2?.textCase,
        textDecoration: theme?.typography?.h2?.textDecoration,
      },
      h3: {
        fontFamily: baseFont.style.fontFamily,
        fontWeight: theme?.typography?.h3?.fontWeight,
        lineHeight: theme?.typography?.h3?.lineHeight,
        fontSize: theme?.typography?.h3?.fontSize,
        letterSpacing: theme?.typography?.h3?.letterSpacing,
        paragraphSpacing: theme?.typography?.h3?.paragraphSpacing,
        paragraphIndent: theme?.typography?.h3?.paragraphIndent,
        textCase: theme?.typography?.h3?.textCase,
        textDecoration: theme?.typography?.h3?.textDecoration,
      },
      h4: {
        fontFamily: baseFont.style.fontFamily,
        fontWeight: theme?.typography?.h4?.fontWeight,
        lineHeight: theme?.typography?.h4?.lineHeight,
        fontSize: theme?.typography?.h4?.fontSize,
        letterSpacing: theme?.typography?.h4?.letterSpacing,
        paragraphSpacing: theme?.typography?.h4?.paragraphSpacing,
        paragraphIndent: theme?.typography?.h4?.paragraphIndent,
        textCase: theme?.typography?.h4?.textCase,
        textDecoration: theme?.typography?.h4?.textDecoration,
      },
      h5: {
        fontFamily: baseFont.style.fontFamily,
        fontWeight: theme?.typography?.h5?.fontWeight,
        lineHeight: theme?.typography?.h5?.lineHeight,
        fontSize: theme?.typography?.h5?.fontSize,
        letterSpacing: theme?.typography?.h5?.letterSpacing,
        paragraphSpacing: theme?.typography?.h5?.paragraphSpacing,
        paragraphIndent: theme?.typography?.h5?.paragraphIndent,
        textCase: theme?.typography?.h5?.textCase,
        textDecoration: theme?.typography?.h5?.textDecoration,
      },
      h6: {
        fontFamily: baseFont.style.fontFamily,
        fontWeight: theme?.typography?.h6?.fontWeight,
        lineHeight: theme?.typography?.h6?.lineHeight,
        fontSize: theme?.typography?.h6?.fontSize,
        letterSpacing: theme?.typography?.h6?.letterSpacing,
        paragraphSpacing: theme?.typography?.h6?.paragraphSpacing,
        paragraphIndent: theme?.typography?.h6?.paragraphIndent,
        textCase: theme?.typography?.h6?.textCase,
        textDecoration: theme?.typography?.h6?.textDecoration,
      },
      body1: {
        fontFamily: baseFont.style.fontFamily,
        fontWeight: theme?.typography?.body1?.fontWeight,
        lineHeight: theme?.typography?.body1?.lineHeight,
        fontSize: theme?.typography?.body1?.fontSize,
        letterSpacing: theme?.typography?.body1?.letterSpacing,
        paragraphSpacing: theme?.typography?.body1?.paragraphSpacing,
        paragraphIndent: theme?.typography?.body1?.paragraphIndent,
        textCase: theme?.typography?.body1?.textCase,
        textDecoration: theme?.typography?.body1?.textDecoration,
      },
      body2: {
        fontFamily: baseFont.style.fontFamily,
        fontWeight: theme?.typography?.body2?.fontWeight,
        lineHeight: theme?.typography?.body2?.lineHeight,
        fontSize: theme?.typography?.body2?.fontSize,
        letterSpacing: theme?.typography?.body2?.letterSpacing,
        paragraphSpacing: theme?.typography?.body2?.paragraphSpacing,
        paragraphIndent: theme?.typography?.body2?.paragraphIndent,
        textCase: theme?.typography?.body2?.textCase,
        textDecoration: theme?.typography?.body2?.textDecoration,
      },
      button: {
        fontFamily: baseFont.style.fontFamily,
        fontWeight: theme?.typography?.button?.fontWeight,
        lineHeight: theme?.typography?.button?.lineHeight,
        fontSize: theme?.typography?.button?.fontSize,
        letterSpacing: theme?.typography?.button?.letterSpacing,
        paragraphSpacing: theme?.typography?.button?.paragraphSpacing,
        paragraphIndent: theme?.typography?.button?.paragraphIndent,
        textCase: theme?.typography?.button?.textCase,
        textDecoration: theme?.typography?.button?.textDecoration,
      },
      caption: {
        fontFamily: baseFont.style.fontFamily,
        fontWeight: theme?.typography?.caption?.fontWeight,
        lineHeight: theme?.typography?.caption?.lineHeight,
        fontSize: theme?.typography?.caption?.fontSize,
        letterSpacing: theme?.typography?.caption?.letterSpacing,
        paragraphSpacing: theme?.typography?.caption?.paragraphSpacing,
        paragraphIndent: theme?.typography?.caption?.paragraphIndent,
        textCase: theme?.typography?.caption?.textCase,
        textDecoration: theme?.typography?.caption?.textDecoration,
      },
      overline: {
        fontFamily: baseFont.style.fontFamily,
        fontWeight: theme?.typography?.overline?.fontWeight,
        lineHeight: theme?.typography?.overline?.lineHeight,
        fontSize: theme?.typography?.overline?.fontSize,
        letterSpacing: theme?.typography?.overline?.letterSpacing,
        paragraphSpacing: theme?.typography?.overline?.paragraphSpacing,
        paragraphIndent: theme?.typography?.overline?.paragraphIndent,
        textCase: theme?.typography?.overline?.textCase,
        textDecoration: theme?.typography?.overline?.textDecoration,
      },
    },
  };
};
